
package unisoft.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FNSINNFIODRSvc_24", targetNamespace = "http://ws.unisoft/", wsdlLocation = "file:/D:/New%20folder%20(3)/smev/v_2_4/FNSINNFIODRSvc.wsdl")
public class FNSINNFIODRSvc24
    extends Service
{

    private final static URL FNSINNFIODRSVC24_WSDL_LOCATION;
    private final static WebServiceException FNSINNFIODRSVC24_EXCEPTION;
    private final static QName FNSINNFIODRSVC24_QNAME = new QName("http://ws.unisoft/", "FNSINNFIODRSvc_24");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/New%20folder%20(3)/smev/v_2_4/FNSINNFIODRSvc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FNSINNFIODRSVC24_WSDL_LOCATION = url;
        FNSINNFIODRSVC24_EXCEPTION = e;
    }

    public FNSINNFIODRSvc24() {
        super(__getWsdlLocation(), FNSINNFIODRSVC24_QNAME);
    }

    public FNSINNFIODRSvc24(WebServiceFeature... features) {
        super(__getWsdlLocation(), FNSINNFIODRSVC24_QNAME, features);
    }

    public FNSINNFIODRSvc24(URL wsdlLocation) {
        super(wsdlLocation, FNSINNFIODRSVC24_QNAME);
    }

    public FNSINNFIODRSvc24(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FNSINNFIODRSVC24_QNAME, features);
    }

    public FNSINNFIODRSvc24(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FNSINNFIODRSvc24(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FNSINNFIODRSvc24Port
     */
    @WebEndpoint(name = "FNSINNFIODRSvc_24Port")
    public FNSINNFIODRSvc24Port getFNSINNFIODRSvc24Port() {
        return super.getPort(new QName("http://ws.unisoft/", "FNSINNFIODRSvc_24Port"), FNSINNFIODRSvc24Port.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FNSINNFIODRSvc24Port
     */
    @WebEndpoint(name = "FNSINNFIODRSvc_24Port")
    public FNSINNFIODRSvc24Port getFNSINNFIODRSvc24Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.unisoft/", "FNSINNFIODRSvc_24Port"), FNSINNFIODRSvc24Port.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FNSINNFIODRSVC24_EXCEPTION!= null) {
            throw FNSINNFIODRSVC24_EXCEPTION;
        }
        return FNSINNFIODRSVC24_WSDL_LOCATION;
    }

}
